/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#include "BerthDetailData.h"

static int
memb_numberOfBerths_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 999)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_numberOfBerths_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 10,  10,  1,  999 }	/* (1..999) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static int asn_DFL_4_set_1(int set_value, void **sptr) {
	CompartmentGenderType_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 1 */
		*st = 1;
		return 0;
	} else {
		/* Test default value 1 */
		return (*st == 1);
	}
}
static asn_TYPE_member_t asn_MBR_BerthDetailData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BerthDetailData, berthType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BerthTypeType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"berthType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BerthDetailData, numberOfBerths),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_numberOfBerths_constraint_1,
		&asn_PER_memb_numberOfBerths_constr_3,
		0,
		"numberOfBerths"
		},
	{ ATF_POINTER, 1, offsetof(struct BerthDetailData, gender),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CompartmentGenderType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		asn_DFL_4_set_1,	/* DEFAULT 1 */
		"gender"
		},
};
static const int asn_MAP_BerthDetailData_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_BerthDetailData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BerthDetailData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* berthType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfBerths */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* gender */
};
static asn_SEQUENCE_specifics_t asn_SPC_BerthDetailData_specs_1 = {
	sizeof(struct BerthDetailData),
	offsetof(struct BerthDetailData, _asn_ctx),
	asn_MAP_BerthDetailData_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_BerthDetailData_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BerthDetailData = {
	"BerthDetailData",
	"BerthDetailData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BerthDetailData_tags_1,
	sizeof(asn_DEF_BerthDetailData_tags_1)
		/sizeof(asn_DEF_BerthDetailData_tags_1[0]), /* 1 */
	asn_DEF_BerthDetailData_tags_1,	/* Same as above */
	sizeof(asn_DEF_BerthDetailData_tags_1)
		/sizeof(asn_DEF_BerthDetailData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BerthDetailData_1,
	3,	/* Elements count */
	&asn_SPC_BerthDetailData_specs_1	/* Additional specs */
};

