/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_DeltaCoordinates_H_
#define	_DeltaCoordinates_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeltaCoordinates */
typedef struct DeltaCoordinates {
	long	 longitude;
	long	 latitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeltaCoordinates_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeltaCoordinates;

#ifdef __cplusplus
}
#endif

#endif	/* _DeltaCoordinates_H_ */
#include <asn_internal.h>
