/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_GeoCoordinateType_H_
#define	_GeoCoordinateType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GeoUnitType.h"
#include "GeoCoordinateSystemType.h"
#include "HemisphereLongitudeType.h"
#include "HemisphereLatitudeType.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GeoCoordinateType */
typedef struct GeoCoordinateType {
	GeoUnitType_t	*geoUnit	/* DEFAULT 2 */;
	GeoCoordinateSystemType_t	 coordinateSystem	/* DEFAULT 0 */;
	HemisphereLongitudeType_t	 hemisphereLongitude	/* DEFAULT 0 */;
	HemisphereLatitudeType_t	 hemisphereLatitude	/* DEFAULT 0 */;
	long	 longitude;
	long	 latitude;
	GeoUnitType_t	*accuracy	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeoCoordinateType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeoCoordinateType;

#ifdef __cplusplus
}
#endif

#endif	/* _GeoCoordinateType_H_ */
#include <asn_internal.h>
