/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_LineType_H_
#define	_LineType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <IA5String.h>
#include "CodeTableType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LineType */
typedef struct LineType {
	long	*carrierNum	/* OPTIONAL */;
	IA5String_t	*carrierIA5	/* OPTIONAL */;
	struct LineType__lineId {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *lineId;
	CodeTableType_t	 stationCodeTable	/* DEFAULT 0 */;
	long	*entryStationNum	/* OPTIONAL */;
	IA5String_t	*entryStationIA5	/* OPTIONAL */;
	long	*terminatingStationNum	/* OPTIONAL */;
	IA5String_t	*terminatingStationIA5	/* OPTIONAL */;
	long	*city	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LineType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LineType;

#ifdef __cplusplus
}
#endif

#endif	/* _LineType_H_ */
#include <asn_internal.h>
