/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_ParkingGroundData_H_
#define	_ParkingGroundData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <NativeInteger.h>
#include <UTF8String.h>
#include "CodeTableType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtensionData;
struct VatDetailType;

/* ParkingGroundData */
typedef struct ParkingGroundData {
	IA5String_t	*referenceIA5	/* OPTIONAL */;
	long	*referenceNum	/* OPTIONAL */;
	IA5String_t	 parkingGroundId;
	long	 fromParkingDate;
	long	 untilParkingDate	/* DEFAULT 0 */;
	long	*productOwnerNum	/* OPTIONAL */;
	IA5String_t	*productOwnerIA5	/* OPTIONAL */;
	long	*productIdNum	/* OPTIONAL */;
	IA5String_t	*productIdIA5	/* OPTIONAL */;
	IA5String_t	*accessCode	/* OPTIONAL */;
	UTF8String_t	 location;
	CodeTableType_t	 stationCodeTable	/* DEFAULT 0 */;
	long	*stationNum	/* OPTIONAL */;
	UTF8String_t	*stationIA5	/* OPTIONAL */;
	UTF8String_t	*specialInformation	/* OPTIONAL */;
	UTF8String_t	*entryTrack	/* OPTIONAL */;
	IA5String_t	*numberPlate	/* OPTIONAL */;
	long	*price	/* OPTIONAL */;
	struct ParkingGroundData__vatDetail {
		A_SEQUENCE_OF(struct VatDetailType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vatDetail;
	struct ExtensionData	*extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParkingGroundData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParkingGroundData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtensionData.h"
#include "VatDetailType.h"

#endif	/* _ParkingGroundData_H_ */
#include <asn_internal.h>
