/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_PassData_H_
#define	_PassData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <IA5String.h>
#include <UTF8String.h>
#include "TravelClassType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ValidityPeriodDetailType;
struct TrainValidityType;
struct ExtensionData;
struct RegionalValidityType;
struct TariffType;
struct VatDetailType;

/* PassData */
typedef struct PassData {
	long	*referenceNum	/* OPTIONAL */;
	IA5String_t	*referenceIA5	/* OPTIONAL */;
	long	*productOwnerNum	/* OPTIONAL */;
	IA5String_t	*productOwnerIA5	/* OPTIONAL */;
	long	*productIdNum	/* OPTIONAL */;
	IA5String_t	*productIdIA5	/* OPTIONAL */;
	long	*passType	/* OPTIONAL */;
	UTF8String_t	*passDescription	/* OPTIONAL */;
	TravelClassType_t	*classCode	/* DEFAULT 2 */;
	long	 validFromDay	/* DEFAULT 0 */;
	long	*validFromTime	/* OPTIONAL */;
	long	*validFromUTCOffset	/* OPTIONAL */;
	long	 validUntilDay	/* DEFAULT 0 */;
	long	*validUntilTime	/* OPTIONAL */;
	long	*validUntilUTCOffset	/* OPTIONAL */;
	struct ValidityPeriodDetailType	*validityPeriodDetails	/* OPTIONAL */;
	long	*numberOfValidityDays	/* OPTIONAL */;
	struct TrainValidityType	*trainValidity	/* OPTIONAL */;
	long	*numberOfPossibleTrips	/* OPTIONAL */;
	long	*numberOfDaysOfTravel	/* OPTIONAL */;
	struct PassData__activatedDay {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *activatedDay;
	struct PassData__countries {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *countries;
	struct PassData__includedCarrierNum {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *includedCarrierNum;
	struct PassData__includedCarrierIA5 {
		A_SEQUENCE_OF(IA5String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *includedCarrierIA5;
	struct PassData__excludedCarrierNum {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *excludedCarrierNum;
	struct PassData__excludedCarrierIA5 {
		A_SEQUENCE_OF(IA5String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *excludedCarrierIA5;
	struct PassData__includedServiceBrands {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *includedServiceBrands;
	struct PassData__excludedServiceBrands {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *excludedServiceBrands;
	struct PassData__validRegion {
		A_SEQUENCE_OF(struct RegionalValidityType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *validRegion;
	struct PassData__tariffs {
		A_SEQUENCE_OF(struct TariffType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tariffs;
	long	*price	/* OPTIONAL */;
	struct PassData__vatDetail {
		A_SEQUENCE_OF(struct VatDetailType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vatDetail;
	UTF8String_t	*infoText	/* OPTIONAL */;
	struct ExtensionData	*extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PassData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PassData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ValidityPeriodDetailType.h"
#include "TrainValidityType.h"
#include "ExtensionData.h"
#include "RegionalValidityType.h"
#include "TariffType.h"
#include "VatDetailType.h"

#endif	/* _PassData_H_ */
#include <asn_internal.h>
