/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_ReservationData_H_
#define	_ReservationData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <IA5String.h>
#include <UTF8String.h>
#include "ServiceType.h"
#include "CodeTableType.h"
#include "TravelClassType.h"
#include "PriceTypeType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PlacesType;
struct CompartmentDetailsType;
struct LuggageRestrictionType;
struct ExtensionData;
struct BerthDetailData;
struct TariffType;
struct VatDetailType;

/* ReservationData */
typedef struct ReservationData {
	long	*trainNum	/* OPTIONAL */;
	IA5String_t	*trainIA5	/* OPTIONAL */;
	long	 departureDate	/* DEFAULT 0 */;
	IA5String_t	*referenceIA5	/* OPTIONAL */;
	long	*referenceNum	/* OPTIONAL */;
	long	*productOwnerNum	/* OPTIONAL */;
	IA5String_t	*productOwnerIA5	/* OPTIONAL */;
	long	*productIdNum	/* OPTIONAL */;
	IA5String_t	*productIdIA5	/* OPTIONAL */;
	long	*serviceBrand	/* OPTIONAL */;
	UTF8String_t	*serviceBrandAbrUTF8	/* OPTIONAL */;
	UTF8String_t	*serviceBrandNameUTF8	/* OPTIONAL */;
	ServiceType_t	 service	/* DEFAULT 0 */;
	CodeTableType_t	*stationCodeTable	/* DEFAULT 1 */;
	long	*fromStationNum	/* OPTIONAL */;
	IA5String_t	*fromStationIA5	/* OPTIONAL */;
	long	*toStationNum	/* OPTIONAL */;
	IA5String_t	*toStationIA5	/* OPTIONAL */;
	UTF8String_t	*fromStationNameUTF8	/* OPTIONAL */;
	UTF8String_t	*toStationNameUTF8	/* OPTIONAL */;
	long	 departureTime;
	long	*departureUTCOffset	/* OPTIONAL */;
	long	 arrivalDate	/* DEFAULT 0 */;
	long	*arrivalTime	/* OPTIONAL */;
	long	*arrivalUTCOffset	/* OPTIONAL */;
	struct ReservationData__carrierNum {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *carrierNum;
	struct ReservationData__carrierIA5 {
		A_SEQUENCE_OF(IA5String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *carrierIA5;
	TravelClassType_t	*classCode	/* DEFAULT 2 */;
	IA5String_t	*serviceLevel	/* OPTIONAL */;
	struct PlacesType	*places	/* OPTIONAL */;
	struct PlacesType	*additionalPlaces	/* OPTIONAL */;
	struct PlacesType	*bicyclePlaces	/* OPTIONAL */;
	struct CompartmentDetailsType	*compartmentDetails	/* OPTIONAL */;
	long	 numberOfOverbooked	/* DEFAULT 0 */;
	struct ReservationData__berth {
		A_SEQUENCE_OF(struct BerthDetailData) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *berth;
	struct ReservationData__tariff {
		A_SEQUENCE_OF(struct TariffType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tariff;
	PriceTypeType_t	*priceType	/* DEFAULT 3 */;
	long	*price	/* OPTIONAL */;
	struct ReservationData__vatDetail {
		A_SEQUENCE_OF(struct VatDetailType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vatDetail;
	long	 typeOfSupplement	/* DEFAULT 0 */;
	long	 numberOfSupplements	/* DEFAULT 0 */;
	struct LuggageRestrictionType	*luggage	/* OPTIONAL */;
	UTF8String_t	*infoText	/* OPTIONAL */;
	struct ExtensionData	*extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReservationData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReservationData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PlacesType.h"
#include "CompartmentDetailsType.h"
#include "LuggageRestrictionType.h"
#include "ExtensionData.h"
#include "BerthDetailData.h"
#include "TariffType.h"
#include "VatDetailType.h"

#endif	/* _ReservationData_H_ */
#include <asn_internal.h>
