/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_RouteSectionType_H_
#define	_RouteSectionType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CodeTableType.h"
#include <NativeInteger.h>
#include <IA5String.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RouteSectionType */
typedef struct RouteSectionType {
	CodeTableType_t	 stationCodeTable	/* DEFAULT 0 */;
	long	*fromStationNum	/* OPTIONAL */;
	IA5String_t	*fromStationIA5	/* OPTIONAL */;
	long	*toStationNum	/* OPTIONAL */;
	IA5String_t	*toStationIA5	/* OPTIONAL */;
	UTF8String_t	*fromStationNameUTF8	/* OPTIONAL */;
	UTF8String_t	*toStationNameUTF8	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RouteSectionType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RouteSectionType;

#ifdef __cplusplus
}
#endif

#endif	/* _RouteSectionType_H_ */
#include <asn_internal.h>
