/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_ServiceType_H_
#define	_ServiceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceType {
	ServiceType_seat	= 0,
	ServiceType_couchette	= 1,
	ServiceType_berth	= 2,
	ServiceType_carcarriage	= 3
} e_ServiceType;

/* ServiceType */
typedef long	 ServiceType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceType;
asn_struct_free_f ServiceType_free;
asn_struct_print_f ServiceType_print;
asn_constr_check_f ServiceType_constraint;
ber_type_decoder_f ServiceType_decode_ber;
der_type_encoder_f ServiceType_encode_der;
xer_type_decoder_f ServiceType_decode_xer;
xer_type_encoder_f ServiceType_encode_xer;
per_type_decoder_f ServiceType_decode_uper;
per_type_encoder_f ServiceType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceType_H_ */
#include <asn_internal.h>
