/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_StationPassageData_H_
#define	_StationPassageData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <NativeInteger.h>
#include <UTF8String.h>
#include "CodeTableType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtensionData;

/* StationPassageData */
typedef struct StationPassageData {
	IA5String_t	*referenceIA5	/* OPTIONAL */;
	long	*referenceNum	/* OPTIONAL */;
	long	*productOwnerNum	/* OPTIONAL */;
	IA5String_t	*productOwnerIA5	/* OPTIONAL */;
	long	*productIdNum	/* OPTIONAL */;
	IA5String_t	*productIdIA5	/* OPTIONAL */;
	UTF8String_t	*productName	/* OPTIONAL */;
	CodeTableType_t	 stationCodeTable	/* DEFAULT 0 */;
	struct StationPassageData__stationNum {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *stationNum;
	struct StationPassageData__stationIA5 {
		A_SEQUENCE_OF(IA5String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *stationIA5;
	struct StationPassageData__stationNameUTF8 {
		A_SEQUENCE_OF(UTF8String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *stationNameUTF8;
	struct StationPassageData__areaCodeNum {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *areaCodeNum;
	struct StationPassageData__areaCodeIA5 {
		A_SEQUENCE_OF(IA5String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *areaCodeIA5;
	struct StationPassageData__areaNameUTF8 {
		A_SEQUENCE_OF(UTF8String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *areaNameUTF8;
	long	 validFromDay;
	long	*validFromTime	/* OPTIONAL */;
	long	*validFromUTCOffset	/* OPTIONAL */;
	long	 validUntilDay	/* DEFAULT 0 */;
	long	*validUntilTime	/* OPTIONAL */;
	long	*validUntilUTCOffset	/* OPTIONAL */;
	long	*numberOfDaysValid	/* OPTIONAL */;
	struct ExtensionData	*extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StationPassageData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StationPassageData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtensionData.h"

#endif	/* _StationPassageData_H_ */
#include <asn_internal.h>
