/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_UicRailTicketData_H_
#define	_UicRailTicketData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IssuingData.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TravelerData;
struct ControlData;
struct DocumentData;
struct ExtensionData;

/* UicRailTicketData */
typedef struct UicRailTicketData {
	IssuingData_t	 issuingDetail;
	struct TravelerData	*travelerDetail	/* OPTIONAL */;
	struct UicRailTicketData__transportDocument {
		A_SEQUENCE_OF(struct DocumentData) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *transportDocument;
	struct ControlData	*controlDetail	/* OPTIONAL */;
	struct UicRailTicketData__extension {
		A_SEQUENCE_OF(struct ExtensionData) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *extension;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UicRailTicketData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UicRailTicketData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TravelerData.h"
#include "ControlData.h"
#include "DocumentData.h"
#include "ExtensionData.h"

#endif	/* _UicRailTicketData_H_ */
#include <asn_internal.h>
