var Enum = require('enum');

exports.sBlockTypes = new Enum({
  'Preismodell': 1,
  'Produktklasse Gesamtticket': 2,
  'Produktklasse Hinfahrt': 3,
  'Produktklasse Rückfahrt': 4,
  'Passagiere': 9,
  'Kinder': 12,
  'Klasse': 14,
  'H-Start-Bf': 15,
  'H-Ziel-Bf': 16,
  'R-Start-Bf': 17,
  'R-Ziel-Bf': 18,
  'Vorgangsnr./Flugscheinnr.': 19,
  'Vertragspartner': 20,
  'VIA': 21,
  'Personenname': 23,
  'Preisart': 26,
  'Ausweis-ID': 27,
  'Vorname, Name': 28,
  'Gueltig von': 31,
  'Gueltig bis': 32,
  'Start-Bf-ID': 35,
  'Ziel-Bf-ID': 36,
  'Anzahl Personen': 40,
  'TBD EFS Anzahl': 41,
});
