/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_CardReferenceType_H_
#define	_CardReferenceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <IA5String.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CardReferenceType */
typedef struct CardReferenceType {
	long	*cardIssuerNum	/* OPTIONAL */;
	IA5String_t	*cardIssuerIA5	/* OPTIONAL */;
	long	*cardIdNum	/* OPTIONAL */;
	IA5String_t	*cardIdIA5	/* OPTIONAL */;
	UTF8String_t	*cardName	/* OPTIONAL */;
	long	*cardType	/* OPTIONAL */;
	long	*leadingCardIdNum	/* OPTIONAL */;
	IA5String_t	*leadingCardIdIA5	/* OPTIONAL */;
	long	*trailingCardIdNum	/* OPTIONAL */;
	IA5String_t	*trailingCardIdIA5	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CardReferenceType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CardReferenceType;

#ifdef __cplusplus
}
#endif

#endif	/* _CardReferenceType_H_ */
#include <asn_internal.h>
