/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_CodeTableType_H_
#define	_CodeTableType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CodeTableType {
	CodeTableType_stationUIC	= 0,
	CodeTableType_stationUICReservation	= 1,
	CodeTableType_stationERA	= 2,
	CodeTableType_localCarrierStationCodeTable	= 3,
	CodeTableType_proprietaryIssuerStationCodeTable	= 4
} e_CodeTableType;

/* CodeTableType */
typedef long	 CodeTableType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CodeTableType;
asn_struct_free_f CodeTableType_free;
asn_struct_print_f CodeTableType_print;
asn_constr_check_f CodeTableType_constraint;
ber_type_decoder_f CodeTableType_decode_ber;
der_type_encoder_f CodeTableType_encode_der;
xer_type_decoder_f CodeTableType_decode_xer;
xer_type_encoder_f CodeTableType_encode_xer;
per_type_decoder_f CodeTableType_decode_uper;
per_type_encoder_f CodeTableType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CodeTableType_H_ */
#include <asn_internal.h>
