/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_CompartmentDetailsType_H_
#define	_CompartmentDetailsType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <UTF8String.h>
#include "CompartmentPositionType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CompartmentDetailsType */
typedef struct CompartmentDetailsType {
	long	*coachType	/* OPTIONAL */;
	long	*compartmentType	/* OPTIONAL */;
	long	*specialAllocation	/* OPTIONAL */;
	UTF8String_t	*coachTypeDescr	/* OPTIONAL */;
	UTF8String_t	*compartmentTypeDescr	/* OPTIONAL */;
	UTF8String_t	*specialAllocationDescr	/* OPTIONAL */;
	CompartmentPositionType_t	 position	/* DEFAULT 0 */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CompartmentDetailsType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CompartmentDetailsType;

#ifdef __cplusplus
}
#endif

#endif	/* _CompartmentDetailsType_H_ */
#include <asn_internal.h>
