/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_DocumentData_H_
#define	_DocumentData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ReservationData.h"
#include "CarCarriageReservationData.h"
#include "OpenTicketData.h"
#include "PassData.h"
#include "VoucherData.h"
#include "CustomerCardData.h"
#include "CountermarkData.h"
#include "ParkingGroundData.h"
#include "FIPTicketData.h"
#include "StationPassageData.h"
#include "ExtensionData.h"
#include "DelayConfirmation.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DocumentData__ticket_PR {
	DocumentData__ticket_PR_NOTHING,	/* No components present */
	DocumentData__ticket_PR_reservation,
	DocumentData__ticket_PR_carCarriageReservation,
	DocumentData__ticket_PR_openTicket,
	DocumentData__ticket_PR_pass,
	DocumentData__ticket_PR_voucher,
	DocumentData__ticket_PR_customerCard,
	DocumentData__ticket_PR_counterMark,
	DocumentData__ticket_PR_parkingGround,
	DocumentData__ticket_PR_fipTicket,
	DocumentData__ticket_PR_stationPassage,
	DocumentData__ticket_PR_extension,
	DocumentData__ticket_PR_delayConfirmation,
	/* Extensions may appear below */
	
} DocumentData__ticket_PR;

/* Forward declarations */
struct TokenType;

/* DocumentData */
typedef struct DocumentData {
	struct TokenType	*token	/* OPTIONAL */;
	struct DocumentData__ticket {
		DocumentData__ticket_PR present;
		union DocumentData__ticket_u {
			ReservationData_t	 reservation;
			CarCarriageReservationData_t	 carCarriageReservation;
			OpenTicketData_t	 openTicket;
			PassData_t	 pass;
			VoucherData_t	 voucher;
			CustomerCardData_t	 customerCard;
			CountermarkData_t	 counterMark;
			ParkingGroundData_t	 parkingGround;
			FIPTicketData_t	 fipTicket;
			StationPassageData_t	 stationPassage;
			ExtensionData_t	 extension;
			DelayConfirmation_t	 delayConfirmation;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ticket;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DocumentData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DocumentData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TokenType.h"

#endif	/* _DocumentData_H_ */
#include <asn_internal.h>
