/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_HemisphereLongitudeType_H_
#define	_HemisphereLongitudeType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HemisphereLongitudeType {
	HemisphereLongitudeType_east	= 0,
	HemisphereLongitudeType_west	= 1
} e_HemisphereLongitudeType;

/* HemisphereLongitudeType */
typedef long	 HemisphereLongitudeType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HemisphereLongitudeType;
asn_struct_free_f HemisphereLongitudeType_free;
asn_struct_print_f HemisphereLongitudeType_print;
asn_constr_check_f HemisphereLongitudeType_constraint;
ber_type_decoder_f HemisphereLongitudeType_decode_ber;
der_type_encoder_f HemisphereLongitudeType_encode_der;
xer_type_decoder_f HemisphereLongitudeType_decode_xer;
xer_type_encoder_f HemisphereLongitudeType_encode_xer;
per_type_decoder_f HemisphereLongitudeType_decode_uper;
per_type_encoder_f HemisphereLongitudeType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HemisphereLongitudeType_H_ */
#include <asn_internal.h>
