/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_IncludedOpenTicketType_H_
#define	_IncludedOpenTicketType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <IA5String.h>
#include "CodeTableType.h"
#include "TravelClassType.h"
#include <UTF8String.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtensionData;
struct RegionalValidityType;
struct TariffType;

/* IncludedOpenTicketType */
typedef struct IncludedOpenTicketType {
	long	*productOwnerNum	/* OPTIONAL */;
	IA5String_t	*productOwnerIA5	/* OPTIONAL */;
	long	*productIdNum	/* OPTIONAL */;
	IA5String_t	*productIdIA5	/* OPTIONAL */;
	long	*externalIssuerId	/* OPTIONAL */;
	long	*issuerAuthorizationId	/* OPTIONAL */;
	CodeTableType_t	 stationCodeTable	/* DEFAULT 0 */;
	struct IncludedOpenTicketType__validRegion {
		A_SEQUENCE_OF(struct RegionalValidityType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *validRegion;
	long	 validFromDay	/* DEFAULT 0 */;
	long	*validFromTime	/* OPTIONAL */;
	long	*validFromUTCOffset	/* OPTIONAL */;
	long	 validUntilDay	/* DEFAULT 0 */;
	long	*validUntilTime	/* OPTIONAL */;
	long	*validUntilUTCOffset	/* OPTIONAL */;
	TravelClassType_t	*classCode	/* OPTIONAL */;
	IA5String_t	*serviceLevel	/* OPTIONAL */;
	struct IncludedOpenTicketType__carrierNum {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *carrierNum;
	struct IncludedOpenTicketType__carrierIA5 {
		A_SEQUENCE_OF(IA5String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *carrierIA5;
	struct IncludedOpenTicketType__includedServiceBrands {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *includedServiceBrands;
	struct IncludedOpenTicketType__excludedServiceBrands {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *excludedServiceBrands;
	struct IncludedOpenTicketType__tariffs {
		A_SEQUENCE_OF(struct TariffType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tariffs;
	UTF8String_t	*infoText	/* OPTIONAL */;
	struct IncludedOpenTicketType__includedTransportType {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *includedTransportType;
	struct IncludedOpenTicketType__excludedTransportType {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *excludedTransportType;
	struct ExtensionData	*extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IncludedOpenTicketType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IncludedOpenTicketType;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtensionData.h"
#include "RegionalValidityType.h"
#include "TariffType.h"

#endif	/* _IncludedOpenTicketType_H_ */
#include <asn_internal.h>
