/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#include "LuggageRestrictionType.h"

static int
memb_maxHandLuggagePieces_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 99)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_maxNonHandLuggagePieces_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 99)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_maxHandLuggagePieces_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  99 }	/* (0..99) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_maxNonHandLuggagePieces_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  99 }	/* (0..99) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static int asn_DFL_2_set_3(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 3 */
		*st = 3;
		return 0;
	} else {
		/* Test default value 3 */
		return (*st == 3);
	}
}
static int asn_DFL_3_set_1(int set_value, void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 1 */
		*st = 1;
		return 0;
	} else {
		/* Test default value 1 */
		return (*st == 1);
	}
}
static asn_TYPE_member_t asn_MBR_registeredLuggage_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RegisteredLuggageType,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_registeredLuggage_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_registeredLuggage_specs_4 = {
	sizeof(struct LuggageRestrictionType__registeredLuggage),
	offsetof(struct LuggageRestrictionType__registeredLuggage, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_registeredLuggage_4 = {
	"registeredLuggage",
	"registeredLuggage",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_registeredLuggage_tags_4,
	sizeof(asn_DEF_registeredLuggage_tags_4)
		/sizeof(asn_DEF_registeredLuggage_tags_4[0]) - 1, /* 1 */
	asn_DEF_registeredLuggage_tags_4,	/* Same as above */
	sizeof(asn_DEF_registeredLuggage_tags_4)
		/sizeof(asn_DEF_registeredLuggage_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_registeredLuggage_4,
	1,	/* Single element */
	&asn_SPC_registeredLuggage_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_LuggageRestrictionType_1[] = {
	{ ATF_POINTER, 3, offsetof(struct LuggageRestrictionType, maxHandLuggagePieces),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_maxHandLuggagePieces_constraint_1,
		&asn_PER_memb_maxHandLuggagePieces_constr_2,
		asn_DFL_2_set_3,	/* DEFAULT 3 */
		"maxHandLuggagePieces"
		},
	{ ATF_POINTER, 2, offsetof(struct LuggageRestrictionType, maxNonHandLuggagePieces),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_maxNonHandLuggagePieces_constraint_1,
		&asn_PER_memb_maxNonHandLuggagePieces_constr_3,
		asn_DFL_3_set_1,	/* DEFAULT 1 */
		"maxNonHandLuggagePieces"
		},
	{ ATF_POINTER, 1, offsetof(struct LuggageRestrictionType, registeredLuggage),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_registeredLuggage_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"registeredLuggage"
		},
};
static const int asn_MAP_LuggageRestrictionType_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_LuggageRestrictionType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LuggageRestrictionType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* maxHandLuggagePieces */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* maxNonHandLuggagePieces */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* registeredLuggage */
};
static asn_SEQUENCE_specifics_t asn_SPC_LuggageRestrictionType_specs_1 = {
	sizeof(struct LuggageRestrictionType),
	offsetof(struct LuggageRestrictionType, _asn_ctx),
	asn_MAP_LuggageRestrictionType_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_LuggageRestrictionType_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LuggageRestrictionType = {
	"LuggageRestrictionType",
	"LuggageRestrictionType",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LuggageRestrictionType_tags_1,
	sizeof(asn_DEF_LuggageRestrictionType_tags_1)
		/sizeof(asn_DEF_LuggageRestrictionType_tags_1[0]), /* 1 */
	asn_DEF_LuggageRestrictionType_tags_1,	/* Same as above */
	sizeof(asn_DEF_LuggageRestrictionType_tags_1)
		/sizeof(asn_DEF_LuggageRestrictionType_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LuggageRestrictionType_1,
	3,	/* Elements count */
	&asn_SPC_LuggageRestrictionType_specs_1	/* Additional specs */
};

