/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_OpenTicketData_H_
#define	_OpenTicketData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <IA5String.h>
#include <BOOLEAN.h>
#include "CodeTableType.h"
#include <UTF8String.h>
#include "TravelClassType.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReturnRouteDescriptionType;
struct LuggageRestrictionType;
struct ExtensionData;
struct RegionalValidityType;
struct TariffType;
struct VatDetailType;
struct IncludedOpenTicketType;

/* OpenTicketData */
typedef struct OpenTicketData {
	long	*referenceNum	/* OPTIONAL */;
	IA5String_t	*referenceIA5	/* OPTIONAL */;
	long	*productOwnerNum	/* OPTIONAL */;
	IA5String_t	*productOwnerIA5	/* OPTIONAL */;
	long	*productIdNum	/* OPTIONAL */;
	IA5String_t	*productIdIA5	/* OPTIONAL */;
	long	*extIssuerId	/* OPTIONAL */;
	long	*issuerAuthorizationId	/* OPTIONAL */;
	BOOLEAN_t	 returnIncluded;
	CodeTableType_t	 stationCodeTable	/* DEFAULT 0 */;
	long	*fromStationNum	/* OPTIONAL */;
	IA5String_t	*fromStationIA5	/* OPTIONAL */;
	long	*toStationNum	/* OPTIONAL */;
	IA5String_t	*toStationIA5	/* OPTIONAL */;
	UTF8String_t	*fromStationNameUTF8	/* OPTIONAL */;
	UTF8String_t	*toStationNameUTF8	/* OPTIONAL */;
	UTF8String_t	*validRegionDesc	/* OPTIONAL */;
	struct OpenTicketData__validRegion {
		A_SEQUENCE_OF(struct RegionalValidityType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *validRegion;
	struct ReturnRouteDescriptionType	*returnDescription	/* OPTIONAL */;
	long	 validFromDay	/* DEFAULT 0 */;
	long	*validFromTime	/* OPTIONAL */;
	long	*validFromUTCOffset	/* OPTIONAL */;
	long	 validUntilDay	/* DEFAULT 0 */;
	long	*validUntilTime	/* OPTIONAL */;
	long	*validUntilUTCOffset	/* OPTIONAL */;
	struct OpenTicketData__activatedDay {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *activatedDay;
	TravelClassType_t	*classCode	/* DEFAULT 2 */;
	IA5String_t	*serviceLevel	/* OPTIONAL */;
	struct OpenTicketData__carrierNum {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *carrierNum;
	struct OpenTicketData__carrierIA5 {
		A_SEQUENCE_OF(IA5String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *carrierIA5;
	struct OpenTicketData__includedServiceBrands {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *includedServiceBrands;
	struct OpenTicketData__excludedServiceBrands {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *excludedServiceBrands;
	struct OpenTicketData__tariffs {
		A_SEQUENCE_OF(struct TariffType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tariffs;
	long	*price	/* OPTIONAL */;
	struct OpenTicketData__vatDetail {
		A_SEQUENCE_OF(struct VatDetailType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vatDetail;
	UTF8String_t	*infoText	/* OPTIONAL */;
	struct OpenTicketData__includedAddOns {
		A_SEQUENCE_OF(struct IncludedOpenTicketType) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *includedAddOns;
	struct LuggageRestrictionType	*luggage	/* OPTIONAL */;
	struct OpenTicketData__includedTransportType {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *includedTransportType;
	struct OpenTicketData__excludedTransportType {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *excludedTransportType;
	struct ExtensionData	*extension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OpenTicketData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OpenTicketData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReturnRouteDescriptionType.h"
#include "LuggageRestrictionType.h"
#include "ExtensionData.h"
#include "RegionalValidityType.h"
#include "TariffType.h"
#include "VatDetailType.h"
#include "IncludedOpenTicketType.h"

#endif	/* _OpenTicketData_H_ */
#include <asn_internal.h>
