/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#include "PlacesType.h"

static int
memb_NativeInteger_constraint_7(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 254)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_Member_constr_8 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  1,  254 }	/* (1..254) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_placeIA5_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_placeIA5_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_placeIA5_specs_5 = {
	sizeof(struct PlacesType__placeIA5),
	offsetof(struct PlacesType__placeIA5, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_placeIA5_5 = {
	"placeIA5",
	"placeIA5",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_placeIA5_tags_5,
	sizeof(asn_DEF_placeIA5_tags_5)
		/sizeof(asn_DEF_placeIA5_tags_5[0]) - 1, /* 1 */
	asn_DEF_placeIA5_tags_5,	/* Same as above */
	sizeof(asn_DEF_placeIA5_tags_5)
		/sizeof(asn_DEF_placeIA5_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_placeIA5_5,
	1,	/* Single element */
	&asn_SPC_placeIA5_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_placeNum_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_NativeInteger_constraint_7,
		&asn_PER_memb_Member_constr_8,
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_placeNum_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_placeNum_specs_7 = {
	sizeof(struct PlacesType__placeNum),
	offsetof(struct PlacesType__placeNum, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_placeNum_7 = {
	"placeNum",
	"placeNum",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_placeNum_tags_7,
	sizeof(asn_DEF_placeNum_tags_7)
		/sizeof(asn_DEF_placeNum_tags_7[0]) - 1, /* 1 */
	asn_DEF_placeNum_tags_7,	/* Same as above */
	sizeof(asn_DEF_placeNum_tags_7)
		/sizeof(asn_DEF_placeNum_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_placeNum_7,
	1,	/* Single element */
	&asn_SPC_placeNum_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PlacesType_1[] = {
	{ ATF_POINTER, 5, offsetof(struct PlacesType, coach),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"coach"
		},
	{ ATF_POINTER, 4, offsetof(struct PlacesType, placeString),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"placeString"
		},
	{ ATF_POINTER, 3, offsetof(struct PlacesType, placeDescription),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"placeDescription"
		},
	{ ATF_POINTER, 2, offsetof(struct PlacesType, placeIA5),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_placeIA5_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"placeIA5"
		},
	{ ATF_POINTER, 1, offsetof(struct PlacesType, placeNum),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_placeNum_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"placeNum"
		},
};
static const int asn_MAP_PlacesType_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_PlacesType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PlacesType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* coach */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* placeString */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* placeDescription */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* placeIA5 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* placeNum */
};
static asn_SEQUENCE_specifics_t asn_SPC_PlacesType_specs_1 = {
	sizeof(struct PlacesType),
	offsetof(struct PlacesType, _asn_ctx),
	asn_MAP_PlacesType_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_PlacesType_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PlacesType = {
	"PlacesType",
	"PlacesType",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PlacesType_tags_1,
	sizeof(asn_DEF_PlacesType_tags_1)
		/sizeof(asn_DEF_PlacesType_tags_1[0]), /* 1 */
	asn_DEF_PlacesType_tags_1,	/* Same as above */
	sizeof(asn_DEF_PlacesType_tags_1)
		/sizeof(asn_DEF_PlacesType_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PlacesType_1,
	5,	/* Elements count */
	&asn_SPC_PlacesType_specs_1	/* Additional specs */
};

