/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ASN-Module-RailTicketData"
 * 	found in "/Users/just/Developer/github/uic-918-3/native/u_flex/uicRailTicketData_v3.0.5.asn"
 * 	`asn1c -fcompound-names -gen-PER -pdu=UicRailTicketData`
 */

#ifndef	_PriceTypeType_H_
#define	_PriceTypeType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PriceTypeType {
	PriceTypeType_noPrice	= 0,
	PriceTypeType_reservationFee	= 1,
	PriceTypeType_supplement	= 2,
	PriceTypeType_travelPrice	= 3
} e_PriceTypeType;

/* PriceTypeType */
typedef long	 PriceTypeType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PriceTypeType;
asn_struct_free_f PriceTypeType_free;
asn_struct_print_f PriceTypeType_print;
asn_constr_check_f PriceTypeType_constraint;
ber_type_decoder_f PriceTypeType_decode_ber;
der_type_encoder_f PriceTypeType_encode_der;
xer_type_decoder_f PriceTypeType_decode_xer;
xer_type_encoder_f PriceTypeType_encode_xer;
per_type_decoder_f PriceTypeType_decode_uper;
per_type_encoder_f PriceTypeType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PriceTypeType_H_ */
#include <asn_internal.h>
